#spring:
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/review_movies
#    username: postgres
#    password: 123456
#jpa:
#  properties:
#    hibernate:
#      show_sql: true
#      ddl-auto: update
#      dialect: org.hibernate.dialect.MyS
#      create_empty_composites:
#        enabled: true
#    format_sql: true
#  open-in-view: false # disable this anti pattern
#  show-sql: true
spring:
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/review_films
      username: root
      password: 123456

  jpa:
      show-sql: true
#properties.hibernate.id.new_generator_mappings=false
      hibernate:
          ddl-auto: update
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect




